### ISSUE TITLE
预览地址报错 Uncaught ReferenceError: ElementPlus is not defined

### ISSUE THREAD

**Issue by h7ml** [miyuesc/vue-data-visualizatuion#2]
貌似因为cdn上不锁定版本号，请求的是最新的``ElementPlus `` 导致资源加载失效
![image](https://user-images.githubusercontent.com/55233292/149075385-8c31d957-c3de-41b5-97c3-8a4409cb69c5.png)

**Comment by miyuesc** [comment]
嗯，有这个问题，，，最大的问题是element团队把打包路径改了。。。

**Comment by h7ml** [comment]
提了[pr](https://github.com/miyuesc/vue-data-visualization/pull/3)
